# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.beam <- function(X, type, ronly, D, verbose = TRUE) {
    .Call('_beam_beam', PACKAGE = 'beam', X, type, ronly, D, verbose)
}

